import { db, blogPostsTable } from "@workspace/db";

const posts = [
  {
    title: "Getting Started with Python Data Analysis",
    slug: "getting-started-python-data-analysis",
    content: [
      "# Getting Started with Python Data Analysis",
      "",
      "Python has become the go-to language for data analysis. Libraries like pandas, numpy, and matplotlib make it incredibly easy to explore and visualize data.",
      "",
      "## Setting Up Your Environment",
      "",
      "```python",
      "import pandas as pd",
      "import numpy as np",
      "import matplotlib.pyplot as plt",
      "",
      "df = pd.read_csv('data.csv')",
      "print(df.head())",
      "```",
      "",
      "## Exploratory Data Analysis",
      "",
      "The first step is always understanding your data. Check basic statistics and look for missing values:",
      "",
      "```python",
      "print(df.describe())",
      "print(df.isnull().sum())",
      "",
      "df.hist(figsize=(10, 8))",
      "plt.show()",
      "```",
      "",
      "## Conclusion",
      "",
      "Python makes data analysis accessible and powerful. Start small, experiment often, and build your intuition for what the data is telling you.",
    ].join("\n"),
    excerpt:
      "A practical introduction to data analysis using Python, covering pandas, numpy, and matplotlib for exploratory data analysis.",
    tags: ["Python", "Data Analysis", "pandas", "Tutorial"],
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Building REST APIs with FastAPI",
    slug: "building-rest-apis-fastapi",
    content: [
      "# Building REST APIs with FastAPI",
      "",
      "FastAPI is a modern, fast web framework for building APIs with Python 3.7+. It is based on standard Python type hints and provides automatic interactive documentation.",
      "",
      "## Why FastAPI?",
      "",
      "- **Fast**: Very high performance, on par with NodeJS and Go",
      "- **Easy**: Designed to be easy to use and learn",
      "- **Automatic docs**: Interactive API documentation with Swagger UI",
      "",
      "## A Simple Example",
      "",
      "```python",
      "from fastapi import FastAPI",
      "from pydantic import BaseModel",
      "",
      "app = FastAPI()",
      "",
      "class Item(BaseModel):",
      "    name: str",
      "    price: float",
      "",
      "@app.get('/')",
      "async def root():",
      "    return {'message': 'Hello World'}",
      "",
      "@app.post('/items/')",
      "async def create_item(item: Item):",
      "    return item",
      "```",
      "",
      "## Running Your App",
      "",
      "```bash",
      "uvicorn main:app --reload",
      "```",
      "",
      "Visit `http://localhost:8000/docs` for the automatic Swagger UI.",
      "",
      "## Conclusion",
      "",
      "FastAPI is an excellent choice for building production-ready APIs quickly. Its type safety and automatic documentation make it a joy to work with.",
    ].join("\n"),
    excerpt:
      "Learn how to build production-ready REST APIs using FastAPI, Python's modern async web framework with automatic documentation.",
    tags: ["Python", "FastAPI", "API", "Backend"],
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Mastering Python Decorators",
    slug: "mastering-python-decorators",
    content: [
      "# Mastering Python Decorators",
      "",
      "Decorators are one of Python's most powerful and elegant features. They allow you to modify or extend the behavior of functions without changing their source code.",
      "",
      "## What is a Decorator?",
      "",
      "At its core, a decorator is a function that wraps another function:",
      "",
      "```python",
      "def my_decorator(func):",
      "    def wrapper(*args, **kwargs):",
      "        print('Before function call')",
      "        result = func(*args, **kwargs)",
      "        print('After function call')",
      "        return result",
      "    return wrapper",
      "",
      "@my_decorator",
      "def say_hello(name):",
      "    print(f'Hello, {name}!')",
      "```",
      "",
      "## Practical Use Cases",
      "",
      "### Timing Functions",
      "",
      "```python",
      "import time",
      "import functools",
      "",
      "def timer(func):",
      "    @functools.wraps(func)",
      "    def wrapper(*args, **kwargs):",
      "        start = time.perf_counter()",
      "        result = func(*args, **kwargs)",
      "        end = time.perf_counter()",
      "        print(f'{func.__name__} ran in {end - start:.4f}s')",
      "        return result",
      "    return wrapper",
      "```",
      "",
      "### Caching with lru_cache",
      "",
      "```python",
      "from functools import lru_cache",
      "",
      "@lru_cache(maxsize=128)",
      "def fibonacci(n):",
      "    if n < 2:",
      "        return n",
      "    return fibonacci(n - 1) + fibonacci(n - 2)",
      "```",
      "",
      "## Conclusion",
      "",
      "Decorators are a fundamental Python concept that enables clean, reusable code. Master them and you will write more Pythonic, elegant solutions.",
    ].join("\n"),
    excerpt:
      "A deep dive into Python decorators, how they work, why they are useful, and practical patterns for everyday use.",
    tags: ["Python", "Decorators", "Advanced Python", "Best Practices"],
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
];

async function seed() {
  for (const post of posts) {
    await db
      .insert(blogPostsTable)
      .values(post)
      .onConflictDoNothing({ target: blogPostsTable.slug });
  }
  console.log("Seeded blog posts successfully");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
